###
GET http://localhost:3000/dogs

###
GET http://localhost:3000/dogs/2

###
POST http://localhost:3000/dogs
content-type: application/json

{
  "name": "Scooby Doo",
  "age": 32,
  "breed": "Great Dane"
}

###
PATCH http://localhost:3000/dogs/8
content-type: application/json

{
  "name": "Beathoven",
  "age": 14,
  "breed": "St. Bernard"
}

###
DELETE http://localhost:3000/dogs/9

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "katrina",
  "email": "katrina@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@test.com",
  "password": "password"
}