###
GET http://localhost:3000/dogs

###
GET http://localhost:3000/dogs/2

###
POST http://localhost:3000/dogs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDc5ODc0ODZ9.sL1tU9TmW6TCk08v7rZQNE4Upk8Jbnf2oF2196t3vWM
content-type: application/json

{
  "name": "Scooby Doo",
  "age": 32,
  "breed": "Great Dane"
}

###
PATCH http://localhost:3000/dogs/8
content-type: application/json

{
  "name": "Beathoven",
  "age": 14,
  "breed": "St. Bernard"
}

###
DELETE http://localhost:3000/dogs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5ODgxMjJ9.jsO86Ko_TFtN6L9lEk8uC8_iOO-zSsJVtlf1yK63vME

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "katrina",
  "email": "katrina@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "katrina@test.com",
  "password": "password"
}